### ISSUE TITLE
Doesn't support Jekyll 3.0?

### ISSUE THREAD

**Issue by connorshea** [merlos/jekyll-auto-image#1]
I'm using the current beta of Jekyll 3.0, and I was wondering if there was any specific reason this gem doesn't support it? Running `bundle install` is giving me an error about the jekyll version not meeting the requirements set by the jekyll-auto-image gem.

I don't expect you to rebuild the gem if there are major changes that affect the gem between 2.0 and 3.0, but if it does work on 3.0 it'd be appreciated!

**Comment by merlos** [comment]
Hi Connor!

Thanks for noticing this issue. 

I've just fixed the gem, it was pretty straight forward (for the record: https://github.com/jekyll/jekyll/issues/3353). 

I've just released `jekyll-auto-image-1.0.2.gem`.Try installing that version. If you find any issue, please let me know.

Best, Juan.

**Comment by connorshea** [comment]
Thank you! :tada:
