### ISSUE TITLE
Broken with Jekyll v3?

### ISSUE THREAD

**Issue by aaronwolen** [merlos/jekyll-auto-image#2]
Jekyll 3 throws the following error:

``` bash
/Users/aaron/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/jekyll-3.0.0/lib/jekyll/document.rb:448:in `method_missing': undefined method `transform' for #<Jekyll::Document:0x007ff60483db58> (NoMethodError)
```

**Comment by thisismatu** [comment]
I also noticed the same error as @aaronwolen 

```
Deprecation: Collection#each should be called on the #docs array directly.
Called by /Users/matu/.rvm/gems/ruby-2.2.1/gems/jekyll-auto-image-1.0.2/lib/jekyll-auto-image.rb:26:in `generate'.
jekyll 3.0.0 | Error:  undefined method `transform' for #<Jekyll::Document:0x007ffc9c260ed0>
```

After a bit of searching i found out that in jekyll 3 `site.posts` are a Collection instead of an Array https://github.com/jekyll/jekyll/pull/4055

So by changing the line 26 of jekyll-auto-image.rb as follows fixed the problem for me:

```
site.posts.docs do |post|
```

**Comment by connorshea** [comment]
Same issue for me, would someone kindly open a PR?

**Comment by connorshea** [comment]
@merlos I've opened a PR, could you merge it in?

**Comment by merlos** [comment]
Thanks @connorshea, @aaronwolen and @mlindholm!

Sorry, it took me so long merging.

Version 1.1.0 should fix the issue https://rubygems.org/gems/jekyll-auto-image/versions/1.1.0.

Regards, Juan!

**Comment by yuhiisk** [comment]
In v3.0.1 It is not working...

```
site.posts.docs do |post|
```

**Comment by merlos** [comment]
v1.1.1 https://rubygems.org/gems/jekyll-auto-image/versions/1.1.1 finally fixes this issue.
Please try it out.

The problem was that posts now are instances of `Jekyll:Document` instead of `Jekyll:Post` (v2.x). This affected the way html is rendered.

Thanks folks.
