### ISSUE TITLE
The plugin doesn't find the image on my pages

### ISSUE THREAD

**Issue by nhoizey** [merlos/jekyll-auto-image#6]
Here is an example where the plugin doesn't find the first image:
https://nicolas-hoizey.com/2016/08/cloudinary-fait-la-promotion-de-mon-plugin-jekyll.html

I have this in my `_config.yml`:

``` yaml
image: favicon.jpg
```

**Comment by merlos** [comment]
Hi @nhoizey 

og:image has the image...

**Comment by nhoizey** [comment]
@merlos well, no, the value here comes from this include: https://github.com/nhoizey/nicolas-hoizey.com/blob/master/_includes/first-image-src.html

You can see here:
https://github.com/nhoizey/nicolas-hoizey.com/blob/master/_includes/head.html#L38-L44

When I tried to use your plugin instead, it really didn't find the image.

**Comment by merlos** [comment]
Thanks @nhoizey 

hummm...the regex captures the `<img>`  http://rubular.com/r/9WLZxflW40

I'm wondering if jekyll-auto-image is running before your jekyll-cloudinary plugin... Do you know the order in which plugins are run?

**Comment by nhoizey** [comment]
It should indeed match.

I thought Liquid tags where run when you call the renderer, but it might not be true.

**Comment by merlos** [comment]
It makes sense as you mention that Liquid tags should be called before jekyll-auto-image. But that may be a start point.

Thanks.

**Comment by nhoizey** [comment]
@merlos I tried your plugin once again, and I think I've found why it doesn't find my images.

I use the [Jekyll Cloudinary](https://nhoizey.github.io/jekyll-cloudinary/) plugin for my images, and when your plugin renders Markdown, it doesn't render Liquid tags.

For example, I have this in the Markdown source:

```markdown
I don't want to give 500px more power over my photos, so I have to leave.

{% cloudinary leaving-500px.png alt="500px e-mail announcing my account has been deactivated" %}

Hello Flickr, happy to see [SmugMug freed you from Yahoo](https://www.smugmug.com/together/), [I'm back](http://flickr.com/photos/nicolas-hoizey/)!
```

And this in the `htmled` variable in your plugin:

```html
<p>I don’t want to give 500px more power over my photos, so I have to leave.</p>

<p>{% cloudinary leaving-500px.png alt=”500px e-mail announcing my account has been deactivated” %}</p>

<p>Hello Flickr, happy to see <a href="https://www.smugmug.com/together/">SmugMug freed you from Yahoo</a>, <a href="http://flickr.com/photos/nicolas-hoizey/">I’m back</a>!</p>
```

Links are rendered, but not the `{% cloudinary … %}` tag.

It's logical the regex doesn't find the image.

**Comment by nhoizey** [comment]
For information, I created a new Jekyll plugin that finds such images, with a different way that yours.

My plugin defines a Filter instead of a Generator, so that:
- I can use it on any HTML string
- it doesn't run for every content, when I only want to use it for some of them (for example the latest, for my blog homepage or feed)

Also, if it finds a responsive image with `srcset`, it extracts the largest image from the set.
