### ISSUE TITLE
Not compatible with 3.3.1

### ISSUE THREAD

**Issue by lejacobroy** [merlos/jekyll-auto-image#8]
Hi,
I seem to have a problem with Jekyll 3.3.1 or Liquid 4...
When I compile de website (bundle exec jekyll build), I get this error : 
`Liquid Warning: Liquid syntax error (line 9): Unexpected character   in "{{ site.url }}" in index.html`
Everywhere I use the liquid tag `<img src="{{ post.image }}" />`.
This is why I suspect the problem comes from jekyll-auto-image.
I tried downgrading to jekyll 3.2.1, same problem.

**Comment by merlos** [comment]
Thanks @lejacobroy for the report

I think this issue is related with #6 

Do any of the your URLs have special character? 
Do you use any other plugin?

Thanks Juan.

**Comment by lejacobroy** [comment]
Hi Merlos,
Thanks for the followup, I use Jekyll-Sitemap aswell and there's no special charater in the URL. I resorted to put image: in the front matter on every posts and it fixes the problem (as I don't use auto-image anymore  :( ).
